### ISSUE TITLE
多企业多应用支持

### ISSUE THREAD

**Issue by jinxiaoyi** [binarywang/weixin-java-cp-demo#10]
你好。我现在遇到了一些问题。
通过观察项目的配置文件。  根据agent-id 作为key，来区分。  但是不同企业的agent-id会重复。 
我们公司正好是多企业。能后期支持吗

**Comment by binarywang** [comment]
你的场景不多见，建议自行实现，每个企业建立独立的配置和service实现类

**Comment by jinxiaoyi** [comment]
> 你的场景不多见，建议自行实现，每个企业建立独立的配置和服务实现类

那是是否只需要改造cpServicesMap的key.  框架里面的具体逻辑和key有关系吗?

**Comment by binarywang** [comment]
> > 你的场景不多见，建议自行实现，每个企业建立独立的配置和服务实现类
> 
> 那是是否只需要改造cpServicesMap的key. 框架里面的具体逻辑和key有关系吗? 主要是害怕框架里面有通过agentId来获取Service的

建议自己看源码就清楚了
