### ISSUE TITLE
消息接收验证失败

### ISSUE THREAD

**Issue by shrto** [binarywang/weixin-java-cp-demo#11]
weixin-java-cp-demo/src/main/java/com/github/binarywang/demo/wx/cp/controller/WxPortalController.java 
中执行到此处异常，查看参数（signature, timestamp, nonce, echostr)都正确获取到了，但此处异常

if (wxCpService.checkSignature(signature, timestamp, nonce, echostr)) {
      return new WxCpCryptUtil(wxCpService.getWxCpConfigStorage()).decrypt(echostr);
    }

**Comment by binarywang** [comment]
请分析下异常内容

**Comment by shrto** [comment]
checkSignature 方法有问题吗
