### ISSUE TITLE
/cgi-bin/auth/getuserinfo 返回的字段是userid 小写 但是代码里大写导致获取失败

### ISSUE THREAD

**Issue by dan334540507** [binarywang/weixin-java-cp-demo#33]
public WxCpOauth2UserInfo getAuthUserInfo(String code) throws WxErrorException {
        String responseText = this.mainService.get(String.format(this.mainService.getWxCpConfigStorage().getApiUrl("/cgi-bin/auth/getuserinfo?code=%s"), code), (String)null);
        JsonObject jo = GsonParser.parse(responseText);
        return WxCpOauth2UserInfo.builder().userId(GsonHelper.getString(jo, "UserId")).openId(GsonHelper.getString(jo, "OpenId")).userTicket(GsonHelper.getString(jo, "user_ticket")).externalUserId(GsonHelper.getString(jo, "external_userid")).build();
    }
    这边GsonHelper.getString(jo, "UserId")  应该是 GsonHelper.getString(jo, "userid")
    版本：
     <dependency>
            <groupId>com.github.binarywang</groupId>
            <artifactId>weixin-java-cp</artifactId>
            <version>4.6.0</version>
        </dependency>

**Comment by binarywang** [comment]
欢迎直接在WxJava项目里提交PR修复代码，谢谢！

**Comment by binarywang** [comment]
你用的的版本有些老，最新版已经更新了

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/WxJava/pull/3208
