### ISSUE TITLE
通讯录同步没有agentId，该如何接收信息推送？

### ISSUE THREAD

**Issue by TonyLuo** [binarywang/weixin-java-cp-demo#4]
其他应用都有agentId，但通讯录同步找不到agentId，该如何接收通讯录改动的信息推送？

**Comment by binarywang** [comment]
readme里有说明吧，你没仔细看？

**Comment by TonyLuo** [comment]
没仔细看：）。摘录如下，方便后来的粗心人。
如果是要配置通讯录同步的应用，agentId可以随便配置一个，保证跟下面服务器URL地址里的一致即可
