### ISSUE TITLE
从企业微信下载临时素材的冲突问题

### ISSUE THREAD

**Issue by gongyw01** [binarywang/weixin-java-cp-demo#5]
调用企业微信的获取临时素材（wxCpService.getMediaService().download（）;）接口时候，报错Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.copyToFile(Ljava/io/InputStream;Ljava/io/File;)V，不知道是不是io的pom引入与自己引入的okhttpclientpom依赖有冲突导致的

**Comment by binarywang** [comment]
很显然是版本冲突问题，定位出问题jar包，更换版本即可，详细请阅读wiki相关部分
