### ISSUE TITLE
编译项目时出现以下错误，

### ISSUE THREAD

**Issue by licheng24176150** [binarywang/weixin-java-cp-demo#7]
```
ERROR org.springframework.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'wxCpConfiguration': Invocation of init method failed; nested exception is java.lang.NullPointerException
```
```
Caused by: java.lang.NullPointerException: null
        at com.github.binarywang.demo.wx.cp.config.WxCpConfiguration.initServices(WxCpConfiguration.java:73)
```

**Comment by binarywang** [comment]
错误位置都给你指出了，是不是配置文件没配？

**Comment by licheng24176150** [comment]
已经解决了，麻烦您了，老哥可以加个 微信吗。------------------ 原始邮件 ------------------
发件人: "Binary Wang"<notifications@github.com>
发送时间: 2019年11月26日(星期二) 下午4:28
收件人: "binarywang/weixin-java-cp-demo"<weixin-java-cp-demo@noreply.github.com>;
抄送: "licheng24176150"<24176150@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [binarywang/weixin-java-cp-demo] 编译项目时出现以下错误， (#7)



错误位置都给你指出了，是不是配置文&#x4EF6;没配？
 
&mdash;

**Comment by binarywang** [comment]
首先你这不是编译出错，是运行出错，其次再仔细阅读下首页的说明，不要漏掉什么操作步骤了。
