### ISSUE TITLE
WxCpService

### ISSUE THREAD

**Issue by shrto** [binarywang/weixin-java-cp-demo#8]
本实例中获取WxCpService
只需要通过WxCpConfiguration.getCpService(agentId) 来获取吗
WxCpService是单例吗

**Comment by binarywang** [comment]
你自己看源码不就清楚了吗？

**Comment by binarywang** [comment]
一个 agentId 对应一个实例

**Comment by shrto** [comment]
谢谢， 在controller或其他地方获取WxCpService
是通过WxCpConfiguration.getCpService(agentId) 来获取吗

**Comment by binarywang** [comment]
不管在哪儿，都可以，你没看它是个静态的方法么？

**Comment by shrto** [comment]
好的 ，谢谢
